%YAML:1.0

# common parameters
# support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image"
image1_topic: "/camera/infra2/image"
output_path: "/home/swarm/vision_ws/src/VINS-Fusion/config/realsense_d435i/output"

# cam0_calib: "infra1_office.yaml"
# cam1_calib: "infra2_office.yaml"
# cam0_calib: "fernando_left.yaml"
# cam1_calib: "fernando_right.yaml"
cam0_calib: "infra1_workshop.yaml"
cam1_calib: "infra2_workshop.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# Pinhole-radtan Kalibr extrinsics
# T_ic:  (cam0 to imu0) from Kalibr
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   # Office checkerboard calibration
   # data: [ 0.999942,   -0.00992588, -0.00417986,  0.00142263,
   #         0.00985122,  0.99979801, -0.0175183,   0.01526227,
   #         0.0043529,   0.0174761,   0.99983781,  0.02793272,
   #         0.,          0.,          0.,          1.        ]
   # Fernando's infra1-IMU calibration
   # data: [ 0.99839799, -0.0540042,   0.0168821,  -0.00887848,
   #         0.05534036,  0.9941692,  -0.09254754,  0.05240635,
   #        -0.01178571,  0.09333354,  0.99556514, -0.08658116,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # Workshop checkerboard calibration
   data: [ 0.99998284, -0.00407817,  0.00420533,  0.03380051,
           0.00406038,  0.99998282,  0.00422872,  0.03095945,
          -0.0042225 , -0.00421158,  0.99998222,  0.03248781,
           0.        ,  0.        ,  0.        ,  1.        ]


body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   # Office checkerboard calibration
   # data: [ 0.99991423, -0.01134968, -0.00653535,  0.05218859,
   #         0.01123154,  0.9997778,  -0.01783808,  0.01641299,
   #         0.00673636,  0.01776314,  0.99981953,  0.02796665,
   #         0.,          0.,          0.,          1.        ]
   # Fernando's infra2-IMU calibration
   # data: [ 0.99836368, -0.05410473,  0.01851066,  0.04021025,
   #         0.05559396,  0.99414546, -0.09265055,  0.05527548,
   #        -0.01338946,  0.09352802,  0.99552661, -0.08732515,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # Workshop checkerboard calibration
   data: [ 0.99998336, -0.00387927,  0.00426927,  0.08387113,
           0.00385899,  0.99998127,  0.00474954,  0.03122195,
          -0.00428762, -0.00473298,  0.99997961,  0.03251556,
           0.        ,  0.        ,  0.        ,  1.        ]



# Multiple thread support
multiple_thread: 1

# feature traker paprameters
max_cnt: 150             # max feature number in feature tracking
min_dist: 30             # min distance between two features 
freq: 10                 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0         # ransac threshold (pixel)
show_track: 1            # publish tracking image as topic
flow_back: 1             # perform forward and backward optical flow to improve feature tracking accuracy

# optimization parameters
max_solver_time: 0.04    # max solver itration time (ms), to guarantee real time
max_num_iterations: 8    # max solver itrations, to guarantee real time
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)


acc_n: 0.00186        # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.000187       # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000433       # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 2.66e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805                       # gravity magnitude


# unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

# loop closure parameters
load_previous_pose_graph: 0  # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/swarm/vision_ws/src/VINS-Fusion/config/realsense_d435i/output"  # save and load path
save_image: 0                # save image in pose graph for visualization prupose; you can close this function by setting 0 4